### ISSUE TITLE
Mentorship Passes do not increment when adding the 2nd time

### ISSUE THREAD

**Issue by rawrrencee** [ianleck/is4103-frontend#126]
https://user-images.githubusercontent.com/43084055/114002625-9dcaf000-988f-11eb-923b-d15270d9c5b3.MP4

**Comment by y1bs** [comment]
This one is because the previous patching code on the backend was overwritten and lost so the bug came back again, I've informed Ian already. Will update once it's settled

**Comment by y1bs** [comment]
For now you can edit this file's line 39 on the backend.

![image](https://user-images.githubusercontent.com/39340177/114139967-4043ab80-9942-11eb-9a1c-7661e33f2728.png)

**Comment by y1bs** [comment]
Issue has been resolved in the latest backend
