### ISSUE TITLE
Bug: Sensei account count in widget (Admin Portal) not updated

### ISSUE THREAD

**Issue by natalieloke** [ianleck/is4103-frontend#72]
Currently
<img width="1280" alt="Screenshot 2021-03-18 at 6 15 58 PM" src="https://user-images.githubusercontent.com/41737751/111726194-6a560080-88a3-11eb-81ab-3fce9e74ef34.png">

How it should be (screenshot from 1st System Release Presentation)
<img width="1280" alt="Screenshot 2021-03-18 at 6 15 45 PM" src="https://user-images.githubusercontent.com/41737751/111726200-6de98780-88a3-11eb-8fab-78cec4271a1d.png">

**Comment by rawrrencee** [comment]
issue resolved in B4 Admin Course Requests branch. due to outdated code referencing old admin.status. Have updated to use admin.role
